### ISSUE TITLE
groups doesn't respect write access plugin hooks

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#8002]
the [groups_write_acl_plugin_hook](https://github.com/Elgg/Elgg/blob/1.9/mod/groups/start.php#L558) sets its own values and doesn't respect what other plugin hooks have already done.

use case:
 - A plugin hook unsets $return[ACCESS_PRIVATE]
 - In group contexts this get added again

**Comment by juho-jaakkola** [comment]
This just bit me. On a quick look it seems that correct way to alter the values would be to register your own plugin hook with lower priority, so it gets run after this one.

The whole handler would be useless if it didn't change the values according to the group access mode policy. I don't see how it could respect the previous values and still do its job.

**Comment by jeabakker** [comment]
>This just bit me. On a quick look it seems that correct way to alter the values would be to register your own plugin hook with lower priority, so it gets run after this one.

so higher prio ;)

> The whole handler would be useless if it didn't change the values according to the group access mode policy. I don't see how it could respect the previous values and still do its job.

If the groups plugin had an array of allowed access levels and went through all the current return values and removed anything not in the allowed list it would respect previous alterations not conflicting with the group rules.

**Comment by juho-jaakkola** [comment]
By default the access array includes all access collections. How could the hook know which ones of those should stay intact?

**Comment by jeabakker** [comment]
access collections are not allowed in groups (currently) so remove all except the group acl. This is no different then how it currently works.

the only difference is the approach. Currently is says this **is** the result, the new way would be this is **allowed** in the result.

**Comment by juho-jaakkola** [comment]
In my use case all ACLs need to be available also in group context. Only way to achieve that is to run the custom handler after the group plugin handler.

But yes, it would indeed help in your use case. I'm just wondering whether this should be solved by simply documenting that any alterations should be done after the group handler.

I won't however block it if you want to make such change.

**Comment by juho-jaakkola** [comment]
Update: my use case required me to unregister the handler completely. The result of this issue won't affect it.

**Comment by beck24** [comment]
So what if anything should be done for this ticket?
I see the options as:
1. register the groups plugin hook with a low priority so it runs first and most other plugin hooks run after (any BC issues?  potentially...)
2. do nothing and expect developers to know/figure out to register a later priority plugin hook or unregister the core groups plugin hook

**Comment by jeabakker** [comment]
@beck24 you forgot my option
3. make sure the groups plugin has a list of allowed access settings and unset everything else.

> register the groups plugin hook with a low priority so it runs first and most other plugin hooks run after (any BC issues? potentially...)

Since the group hook is registered at 'permissions', 'all' it will always run after 'permissions', 'user'. Since i think it's a good practice to not register for 'all' events/hooks prio won't matter.

> do nothing and expect developers to know/figure out to register a later priority plugin hook or unregister the core groups plugin hook

no

I'll make a pr with my solution

**Comment by juho-jaakkola** [comment]
I think your suggestion is fine.
